spring.application.name=Sahaayata - A Nutrition Assistance
# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/sahaayata_db
spring.datasource.username=root
spring.datasource.password=Kartik@1422
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# N8N Webhook Base URL (Sirf base domain rakhna hai, last me slash ya webhook mat lagana)
n8n.webhook.url=https://garmin-dependent-millennium-eventually.trycloudflare.com